service: netflix-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  test:
    handler: test.fibHandler
    events:
      - http:
          path: test
          method: get
  compute:
    handler: test.compute
    events:
      - http:
          path: compute
          method: get
  hello:
    handler: test.hello
    memorySize: 128
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline